name: microsandbox
description: A minimal Dart SDK for the Microsandbox project
version: 0.1.0
homepage: https://github.com/microsandbox/microsandbox
repository: https://github.com/microsandbox/microsandbox
issue_tracker: https://github.com/microsandbox/microsandbox/issues
license: Apache-2.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
